### ISSUE TITLE
LR_LinearElement, LR_Feature and LE_Feature

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/iso-19148#6]
- As I understand it, LR_Feature is the class that implements the interface LR_ILinearElement (ISO 19148, section 6.2.5). In GML 3.3 this is replaced by the class LinearElement (GML 3.3, section 9.3.5).
My suggestion is to rename the class LR_Feature to LinearElement.
- LE_Feature class is a subtype of LR_Feature, with optional attribute "event" (ISO 19148, section 6.6.3). I have never really understood the use of that class, and the standard kind of says that is is unneccessary as well: 
> "An application schema is not required to have an explicit LE_Feature subtype. 
Instead, it can create LE_Feature instances by adding the LR_ILinearElement interface and event attribute(s)  to existing application-specific feature classes, such as Road"

My suggestion is to remove LE_Feature. It is not implemented in GML 3.3.

_Originally posted by @jetgeo in https://github.com/ISO-TC211/iso-19148/issues/3#issuecomment-457217229_

**Comment by diegoalexdiaz** [comment]
I'm fine with removing it as well. It has not been a priority in my head since 19148 already accepts implementations without it, but that detail is not obvious in the UML model.

**Comment by diegoalexdiaz** [comment]
While re-reading this issue, I just realized we never discussed your first bullet and the very title.

A Feature and a LinearElement may sometimes be the same entity, but in some cases, they are different. 

E.g. a Road is an example of a Feature. In some cases, a Road is used also as a LinearElement to linearly locate events along it, but sometimes, especially during design and construction phases of a Road, it is its "Alignment" the one used as the LinearElement for Linear Referencing purposes.

In the former case, the Road class is the one implementing LR_ILinearElement, whereas in the latter case, it is the Alignment class implementing such interface.

Thus, LinearElement should not replace LR_Feature.

**Comment by jetgeo** [comment]
Yes, ILinearElement can be implemented in different feature types (e.g. Road or Alignment), I believe that is the purpose of having it as an interface. A feature type can either implement ILinearElement directly or by being a subclass of a class that implements it. 
In 19148, ILinearElement is implemented in the class LR_Feature, while in GML 3.3 it is implemented in the class LinearElement. As far as I can see, these classes have the same purpose, only the name differ. This must be harmonized. Either change the name in the GML implementation or in the standard.

**Comment by diegoalexdiaz** [comment]
I believe the root of this discussion lies in your assumption an Alignment could be another type of feature (i.e. LR_Feature) whereas I'm assuming it may not be (i.e. LR_Curve). ISO19148 also introduces LR_DirectedEdge as another class implementing ILinearElement, different from LR_Feature.

In ISO19148, LinearElement is a union of those three. I took a peek at GML 3.3, and LinearElement seems to be introduced like ISO19148 describes it:

```
<complexType name="LinearElementType">
...
    <choice>
        <element name="feature" type="gml:FeaturePropertyType"/>
        <element name="curve" type="gml:CurvePropertyType"/>
        <element name="edge" type="gml:DirectedEdgePropertyType"/>
    </choice>
    ...
<element name="LinearElement" type="gmllr:LinearElementType" substitutionGroup="gml:AbstractGML"/>
```

Thus, I believe GML 3.3 implementation conforms to ISO19148, so LinearElement should not replace LR_Feature.

**Comment by jetgeo** [comment]
Ok, I think I understand now. 
GML 3.3. specifies that "gmllr:LinearElement implements ISO 19148 LR_LinearElement". So I think you are correct. 
I have believed that only a feature could implement LR_ILinearElement, but I understand now that also a geometry (curve or edge) can implement it. 
Sorry for the confusion :). I'll rename the issue to avoid further confusion!

**Comment by diegoalexdiaz** [comment]
Thanks Knut. Going back to your other proposal (removing LE_Feature), LE_Feature is introduced as an optional subclass of LR_Feature, with an _event_ attribute-array leading to the LE_Event instances associated with it. 

I believe LE_Feature was introduced following a pattern that the original authors of ISO19148 used while introducing roles/relationships. They introduce a new class for them in several cases. E.g.

1. LR_LinearElement class, as a union to reach the LR_ILinearElement implementation.
2. LR_AlongReferent class, only containing the _fromReferent_ relationship as an attribute.
3. LRTR_DualAlongReferent class, only containing the _towardsReferent_ relationship as an attribute.
4. LE_Feature class, only containing the _event_ relationship as an array attribute.

All of these could be seen as potential opportunities for simplification:

1. PositionExpression could refer to an LR_ILinearElement interface directly rather than through a union.
2. LR_AlongReferent could be removed, letting its _fromReferent_ relationship be defined between a DistanceExpression and the LR_Referent directly.
3. LRTR_DualAlongReferent could be removed, letting its _towardsReferent_ relationship be defined between a DistanceExpression and the LR_Referent directly.
4. LE_Feature class could be removed, letting the _locatingOrAttributedFeature_ relationship be defined to the LR_Feature directly.

What confuses me is how to proceed with these opportunities. Should we:
1. modify the existing packages, dropping those classes from them? or...
2. make those classes optional, while specifying that these "simplified" approaches are also accepted?

I'm leaning towards the # 2, but I'm not sure what has been typically done at other standards at ISO.

Knut, do you know of similar "simplification" efforts to other standards?
